spring.application.name=agencia_viagens

# Configuração do banco de dados PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/agencia_viagens
spring.datasource.username=postgres
spring.datasource.password=postgres

# Configuração do Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect